build: false

environment:
  matrix:
    - PYTHON_VERSION: 2.7
      PYTHON_SVER: 27
      MINICONDA: C:\Miniconda
    - PYTHON_VERSION: 3.4
      PYTHON_SVER: 34
      MINICONDA: C:\Miniconda3

init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"

install:
  # Issues have been encountered with installing numpy and scipy on
  # AppVeyor e.g.
  # http://tjelvarolsson.com/blog/how-to-continuously-test-your-python-code-on-windows-using-appveyor/
  # Miniconda is recommended as the way to install these. See also:
  # https://github.com/appveyor/ci/issues/359
  # The following adopts approaches suggested in the above links.
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - "conda create -q -n test-environment python=%PYTHON_VERSION%"
  - activate test-environment

  # Majority of dependencies can be installed with Anaconda
  - conda install numpy scipy matplotlib sympy networkx nose h5py pandas

  # Graphviz & PyGraphviz
  - appveyor DownloadFile "http://graphviz.org/pub/graphviz/stable/windows/graphviz-2.38.zip" -FileName graphviz.zip
  - 7z x graphviz.zip -y > nul
  - set "PATH=%cd%\release\lib\release\dll;%PATH%"
  - pip install https://dl.dropboxusercontent.com/u/6251352/pygraphviz-1.3.1-cp%PYTHON_SVER%-none-win32.whl?dl=1

  # BioNetGen
  - appveyor DownloadFile "http://www.csb.pitt.edu/Faculty/Faeder/?smd_process_download=1&download_id=151" -FileName BioNetGen.zip
  - 7z x BioNetGen.zip -y > nul
  - set "BNGPATH=%cd%\BioNetGen-2.2.6-stable"

  # KaSim and KaSa
  - appveyor DownloadFile "https://github.com/Kappa-Dev/KaSim/releases/download/v4beta/KaSim.exe" -FileName KaSim.exe
  - appveyor DownloadFile "https://github.com/Kappa-Dev/KaSim/releases/download/v4beta/KaSa.exe" -FileName KaSa.exe
  - set "KAPPAPATH=%cd%"

  # StochKit
  - appveyor DownloadFile "https://downloads.sourceforge.net/project/stochkit/StochKit2/StochKit2.0.10/StochKit2.0.10_WINDOWS_LITE.zip" -FileName stochkit.zip
  - 7z x stochkit.zip -y > nul
  - set "STOCHKITPATH=%cd%\StochKit2.0.10_WINDOWS_LITE"

  # Build PySB
  - python setup.py build --build-lib=build/lib
test_script:
  - nosetests build/lib/pysb -a "!gpu"
